DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS freezer;
DROP TABLE IF EXISTS food;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE freezer (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE food (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	servings INTEGER NOT NULL,
	location_id INTEGER NOT NULL,
	chef_id INTEGER NOT NULL,
	added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (chef_id) REFERENCES user (id),
	FOREIGN KEY (location_id) REFERENCES freezer (id)
);
